<?php
    $title = 'Microwave Reciever';
    
    $mainContent = '<h1>'.$title.'</h1><hr><img align="left" src="/AdvancedRocketry/img/microwaveReciever_demo.jpg" /><h2><center>Overview</center></h2><p>&nbsp;&nbsp;&nbsp;&nbsp; Generates power beamed down from Solar satellites placed in orbit.</p>
    <p>The amount of power generated per tick is directly related to the power generated by linked satellites.</p>
    <p>These satellites must be in orbit around the same planet that the Microwave reciever is built on otherwise the satellites will be unable to transmit power.</p>
    <p>Even if the Microwave Reciever is turned off or not connected to a satellite, the satellites in orbit will continue to generate power which can be stored on a satellite\'s internal buffer.</p>
    <p>The reciever itself can be toggled on and off using the GUI in the Microwave Reciever control block</p>
    <p>To connect a satellite to the Microwave Reciever the satellite chip must be placed in one of the item input hatches built into the structure.  This allows the satellite to track where to send the energy.</p>
    <p>Power generated is stored to the Output Plugs built into the structure.</p>
    <p><font color=#CC0000><b>Warning:</b></font> Entities, items, and blocks that happen to be above the Microwave Reciever while in operation will be incinerated!!!</p>
    <hr />
    <p><h2><center>Construction</center></h2></p>
    
    <p><img align="left" src="/AdvancedRocketry/img/microwaveReciever_build1.jpg">&nbsp;&nbsp;&nbsp;&nbsp;The Microwave Reciever is a one block thick multiblock structure where the <font color="#CC0000">red</font> blocks in the image to the left can be made of either Output Plug, Solar Panel, or Item Input Hatches.</p>
    <p>The <font color="#999900">yellow</font> block in the center is where the Microwave Reciever block is placed in the structure.  The remainder of the structure is solar panels.</p>
    <p>Right clicking the Microwave Reciver block should form the multiblock if all the other blocks are in place.</p>
    ';
    
    $infoBarContent = $title.'<hr><img src="/AdvancedRocketry/img/microwaveReciever_block.png" /><hr>Hardness: 3<br />Blast Resistance: 0<br />Requires Tool: Yes<br />Full Block: Yes<br />Sealable: Yes<br />Tile Entity: Yes<hr>Structure Size: 5x1x5<br />Power Generation: Variable';
    include($_SERVER["DOCUMENT_ROOT"].'/AdvancedRocketry/template.php');
?> 
